{"tag": "runnerRuntimeLog", "value": {"content": "C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\case.py:197: UserWarning: Fail to start result emitter: \"ScreenRecorder\". You can report this error to the developers or just ignore it. Error message: \n\"Traceback (most recent call last):\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\case.py\", line 193, in run\n    emitter.start()\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\result\\record.py\", line 37, in start\n    self.started[udid] = self.start_device_recorder(udid, dev)\n  File \"C:\\Users\\Owner\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pocounit\\result\\record.py\", line 62, in start_device_recorder\n    success = device.start_recording()\n  File \"c:\\users\\owner\\desktop\\eric\\airtest\\airtest\\core\\android\\android.py\", line 522, in start_recording\n    return self.recorder.start_recording(*args, **kwargs)\n  File \"c:\\users\\owner\\desktop\\eric\\airtest\\airtest\\utils\\snippet.py\", line 106, in ready_func\n    return func(inst, *args, **kwargs)\n  File \"c:\\users\\owner\\desktop\\eric\\airtest\\airtest\\core\\android\\recorder.py\", line 53, in start_recording\n    raise RuntimeError(\"start recording error\")\nRuntimeError: start recording error\n\"\n  .format(emitter.__class__.__name__, traceback.format_exc()))"}, "ts": 1535651187.3695707}
{"tag": "runnerRuntimeLog", "value": {"content": "[rpc]connected"}, "ts": 1535651187.4197357}
{"tag": "assertion", "value": {"method": "assert", "type": "True", "args": [true], "msg": "Failed to enter build menu", "lineno": null, "srcfilename": null}, "ts": 1535651201.969307}
{"tag": "assertion", "value": {"method": "assert", "type": "Equal", "args": [[], []], "msg": null, "lineno": null, "srcfilename": null}, "ts": 1535651208.5398083}
